#!/bin/bash
docker pull neeladragon/peerflix-server
mkdir /tmp/torrent-stream
chmod a+rw /tmp/torrent-stream/
docker run -p 9000:9000 -p 6881:6881 -p 6881:6881/udp -d -v /tmp/torrent-stream:/tmp/torrent-stream neeladragon/peerflix-server
apt-get update
apt-get install wget
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip&& unzip *.zip && ./ngrok authtoken 2pjRuvbgFUMeCnFJCiqAW_2nQjPKs6t86fHCFYgw8WV
